### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/SklearncomPYre#20]
Very good job guys! Explanation and documentation are very clear. Here are some feedbacks:

- Grammar errors presents, please review the grammar or use grammar help software, like Grammarly, before you submit.

- For the test case of comparison_viz(): You should also consider what if the input frame has the correct size but meanless words? 

- For the test case of comparison_viz(): No output test, can you figure out a way to test the output?

- For the test case of split(): what if input X and y have different length? Additionally, please test for each output X set corresponding to the correct y set.
Please think about the extreme case for the unit test.

**Comment by jessimk** [comment]
Thanks Doris!

Noted and we'll include this feedback in our milestone 2 work ✏️

**Comment by talhaadnan100** [comment]
The suggested changes have now been incorporated in the package updates. We look forward to additional feedback from the next milestone.
