### ISSUE TITLE
Enhancements to train_test_acc_time.py

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/SklearncomPYre#26]
- [x] The first column is titled `Classifier`, since we are also doing regressors, maybe 'Models' is a better name for it
- [x] The sequence of columns ought to be `'Models', 'Train Accuracy', 'Test Accuracy', 'Variance', 'Fit Time (s)', 'Predict Time (s)', 'Total Time (s)'`

Thanks!

**Comment by jessimk** [comment]
Oh! Talha those are really good points 🙌 

@Birinder1469 , I'm not sure but for the second point you might want to try this:

```
cols = ['Classifier','Train Accuracy', 'Test Accuracy', 'Variance', 'Fit Time', 'Predict Time', 'Total Time']
results_df = results_df[cols]
results_df
```

**Comment by Birinder1469** [comment]
Thanks a lot team for the valuable feedback . This order does make our output more elegant.
I have made the changes and pushed. Please review and merge.
Thanks!
