### ISSUE TITLE
🐛  fixing indexing bug in comparison_viz()

### ISSUE THREAD

**Issue by jessimk** [UBC-MDS/SklearncomPYre#30]
```
    if all(isinstance(n, str) for n in [comparison.iloc[:,1][x] for x in np.arange(comparison.shape[0])]) != True:
        raise TypeError("Comparison Models column must only contain type string")
```

`[comparison.iloc[:,1][x]` I think this should be `[comparison.iloc[:,0][x]` so that it's looking at the first column and not the second column. 

@talhaadnan100 any chance you can take a look and change if necessary?

**Comment by jessimk** [comment]
try?

```
    for j in np.arange(0,comparison.shape[0] -1,1):
        if type(comparison.iloc[:,0][j]) != type("string"):
           raise TypeError("Comparison Models column must only contain type string")
```

**Comment by jessimk** [comment]
Found another culprit! 

test_output_comparison_viz() was failing with the `df` that was passed, because had 8 cols. I made a copy without the index col so that it satisfied the 7 col rule and so that the first col is a col of strings in order to satisfy the other test. Should be ok now! 

Will send PR with changes shortly!

**Comment by Birinder1469** [comment]
Fixed it 

Pull Request : https://github.com/UBC-MDS/SklearncomPYre/pull/32
Thanks
