### ISSUE TITLE
Feedback of Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/SklearncomPYre#7]
The output of the first two functions are some type, and the unit test of them may be very similar. Porbably consider something different so you can have different test.
The first two function feels like just one line of code (call score function), maybe add some extension

**Comment by talhaadnan100** [comment]
Thank you for the feedback. The issue was addressed in the issue [here](https://github.ubc.ca/MDS-2018-19/DSCI_524_milestone1_talhaas/issues/1).
